### ISSUE TITLE
KeyError in locations

### ISSUE THREAD

**Issue by Yaldo425** [manwhoami/FriendsOfFriends#1]
When trying the program, I get this error:

```
Traceback (most recent call last):
  File "/Users/******/Desktop/Friends.py", line 151, in <module>
    print HeardItFromAFriendWho(DSID, mmeFMFAppToken, user),
  File "/Users/*****/Desktop/Friends.py", line 95, in HeardItFromAFriendWho
    for y in x["locations"]:#[0]["location"]["address"]:
KeyError: 'locations'

```

**Comment by manwhoami** [comment]
I just pushed an update that has better error handling. This should catch this error and respond to it accordingly.

**Comment by Yaldo425** [comment]
This time all I get is `Error getting locations.`

**Comment by manwhoami** [comment]
This means that you probably do not have any locations on the account. Does the FMF app yield any locations?
